### ISSUE TITLE
Index - list contests

### ISSUE THREAD

**Issue by wubcrow** [young-amateurs-rc/contest-manager#2]
Welcome 
-- 
Cheesy words and basic guidance. 

List of contests
--
*  List grouped by year and sorted descending by date.
* Show name, dates, sponsor, and (eventually) a link to details.

**Comment by galengold** [comment]
create the frontend in https://github.com/young-amateurs-rc/contest-manager/blob/master/contest_manager/templates/index.html

**Comment by wubcrow** [comment]
Do we want to store the welcome text/site name in some sort of config file, so whoever uses our thing can adjust it easily?

Or should it just go into templates.

**Comment by galengold** [comment]
+1 for config file. I like YAML, but up to you.
