### ISSUE TITLE
Contest information page

### ISSUE THREAD

**Issue by thxo** [young-amateurs-rc/contest-manager#3]
- Basically all fields.
- Contest ID in GET request.
- Provide a link to log submission.

**Comment by galengold** [comment]
By parameterizing the info about the contest, it can be easier to generate uniform templates.

Parameters to have in the database:
- [x] contest name
- [x] start time
- [x] end time
- [x] log due date
- [ ] categories
    - [ ] number of operators
    - [ ] number of transmitters
    - [ ] power
- [ ] scoring formula
- [ ] exchange
- [ ] modes
- [ ] bands
- [ ] mults
- [x] rules (catchall for things not covered above)
- To be continued...
